development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: v-munny
  password: kirby3.14

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: v-munny
  password: kirby3.14

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: v-munny
  password: kirby3.14
